# Generated by Django 4.1.2 on 2024-10-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('in_use', 'In Use')], default='free', max_length=10)),
            ],
        ),
    ]
