# Generated by Django 4.1.2 on 2024-10-01 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0002_parkingspot_door_alter_parkingspot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('booked', 'Booked'), ('in_use', 'In Use')], default='free', max_length=10),
        ),
    ]
